In [3]:
import numpy as np

## Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.random.randint(0,10)

2

In [59]:
np.random.randint(0,10,(3,3))

array([[8, 2, 0],
       [6, 9, 7],
       [8, 8, 1]])

In [67]:
np.random.randint(0,100,(10,10,10))

array([[[37, 30, 10, 42, 56, 18, 31,  0, 22, 54],
        [ 3, 51,  6, 14, 36, 64,  9, 25, 20, 72],
        [58, 51, 95,  3, 38, 15, 13, 55, 27, 58],
        [87, 25, 88, 65, 44, 84, 39, 28, 53, 86],
        [72, 79, 70, 31, 28, 83, 40, 56, 99, 81],
        [ 1, 63, 29, 17, 50, 60, 62, 29, 40, 86],
        [81, 73, 35, 24, 90, 22, 86, 22, 26, 30],
        [35, 42, 96, 93, 57, 13, 82, 92, 43, 64],
        [ 9, 14, 79, 75, 87, 76, 51, 81, 39, 84],
        [86, 49, 30, 14, 40, 69, 87, 80, 55, 19]],

       [[10, 41, 81, 75, 53, 75, 68, 45, 24, 39],
        [23, 78, 53, 47, 74, 87, 93, 76, 89,  2],
        [10, 31,  8, 83, 28, 51,  6, 19, 21, 85],
        [60, 83, 90, 16, 71, 56, 30, 11, 80, 71],
        [97, 28, 17,  8,  5, 76, 11, 18, 92, 14],
        [69, 60, 85, 40,  5, 79, 18, 92, 30, 60],
        [76, 24, 47, 94, 99, 82, 60, 67,  2, 70],
        [76, 70, 83, 64, 22, 91, 97,  0, 61, 30],
        [87, 99,  5, 69, 13, 50, 68, 66, 37, 71],
        [ 2, 99, 33, 87, 21,  0, 86, 66, 14, 46]

In [64]:
np.linspace(0,100,1000)

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

In [65]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Operations

In [76]:
np.random.seed(102) 
arr = np.random.randint(0,100,15)

In [77]:
arr

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3])

In [78]:
arr2 = np.random.randint(0,100,10)

In [79]:
arr2

array([96,  0, 80, 71, 25, 28, 27, 71, 30,  4])

In [80]:
arr.max()

82

In [81]:
arr.min()

0

In [82]:
arr.mean()

49.8

In [83]:
arr.argmin()

0

In [84]:
arr.argmax()

12

In [85]:
arr.shape

(15,)

In [88]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 15 into shape (2,7)

## Indexing

In [89]:
mat = np.arange(0,100).reshape(10,10)

In [90]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
row = 0
col = 1

In [92]:
mat[0,1]

1

In [93]:
# With Slices
mat[:,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
mat[:,-2:]

array([[ 8,  9],
       [18, 19],
       [28, 29],
       [38, 39],
       [48, 49],
       [58, 59],
       [68, 69],
       [78, 79],
       [88, 89],
       [98, 99]])

In [36]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

## Masking

In [37]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [44]:
mat[(mat>50) & (mat<70)]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

# Great Job!